#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from collections import OrderedDict
from datetime import datetime
from pathlib import Path
import subprocess
import json
import sys


JSON_FILENAME = Path.home().joinpath(".local/share/trans_shell/my_dict.json")
TMP_JSON_FILENAME = "/tmp/my_dict.json"
DISPLAY_COUNT_KEY = "display-from-local-dict-to-tmux-count"
DISPLAY_RUST_NEWS = "display-rust-news-to-tmux-flag"


def update_dict_to_file(trans_string: str) -> None:
    if not (trans_list := trans_string.splitlines()):
        return None

    trans_word = trans_list[0].strip()
    try:
        with open(JSON_FILENAME, "r", encoding="utf-8", errors="ignore") as f:
            trans_dict = json.load(f, object_pairs_hook=OrderedDict)
            if trans_word in trans_dict:
                return None
    except FileNotFoundError:
        trans_dict = OrderedDict()

    if any(sub in trans_list for sub in ["Synonyms", "Examples"]):
        if trans_list[1].startswith("/") and trans_list[1].endswith("/"):
            trans_list = [f"{trans_word} {trans_list[1]}"] + trans_list[2:]
        trans_dict.update({trans_word: "\n".join(trans_list)})
        with open(JSON_FILENAME, "w", encoding="utf-8") as f:
            json.dump(trans_dict, f, indent=4)


def python_trans(args: list, from_vim_flag: bool) -> str:
    trans_bin = Path.home().joinpath(".local/bin/trans_shell").as_posix()
    args_list = ["timeout", "3", "bash", trans_bin] + args
    fd = subprocess.Popen(args_list, stdout=subprocess.PIPE)
    if (t := fd.communicate()[0].decode("utf-8")) and (not from_vim_flag):
        update_dict_to_file(t)
    return t


def add_colour(normal_str: str) -> str:
    # https://stackoverflow.com/a/28938235
    COLOUR_OFF = '\033[0m'
    COLOUR_CYAN = '\033[0;36m'
    return f"{COLOUR_CYAN}{normal_str}{COLOUR_OFF}"


def display_trans() -> str:
    try:
        with open(JSON_FILENAME, "r", encoding="utf-8") as f:
            trans_dict = json.load(f, object_pairs_hook=OrderedDict)
    except FileNotFoundError:
        return f"{JSON_FILENAME} not exist"

    try:
        with open(TMP_JSON_FILENAME, "r", encoding="utf-8") as f:
            tmp_trans_dict = json.load(f, object_pairs_hook=OrderedDict)
    except FileNotFoundError:
        tmp_trans_dict = {
            DISPLAY_COUNT_KEY: 0,
            DISPLAY_RUST_NEWS: False
        }

    if tmp_trans_dict[DISPLAY_RUST_NEWS]:
        tmp_trans_dict[DISPLAY_RUST_NEWS] = False
        output = subprocess.Popen(
            "rustnews", stdout=subprocess.PIPE).communicate()[0].decode()
    else:
        display_cnt = tmp_trans_dict[DISPLAY_COUNT_KEY]
        if display_cnt >= len(trans_dict) - 1:
            tmp_trans_dict[DISPLAY_COUNT_KEY] = 0
        else:
            tmp_trans_dict[DISPLAY_COUNT_KEY] = display_cnt + 1
        output = list(trans_dict.values())[display_cnt]

        now_hour = datetime.now().hour
        # in working hour between 8:00 ~ 18:00
        # display news after learning 10 words
        # to avoid hitting the api request rate
        if ((now_hour > 8 and now_hour < 18)
                and (display_cnt > 0 and display_cnt % 10 == 0)):
            tmp_trans_dict[DISPLAY_RUST_NEWS] = True
    with open(TMP_JSON_FILENAME, "w", encoding="utf-8") as f:
        json.dump(tmp_trans_dict, f, indent=4)
    return output.rstrip()


if __name__ == "__main__":
    if "--display-from-local-dict" in sys.argv:
        print(f"\n{add_colour(display_trans())}")
    else:
        if from_vim_flag := ("--from-vim" in sys.argv):
            sys.argv.remove("--from-vim")
        print(python_trans(sys.argv[1:], from_vim_flag))
